name: action-one
on:
  workflow_dispatch:

env:
    python_ver: 3.2
    install_python: false

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Check version
              run: |
                sys_py_ver=$( python --version )
                sys_py_ver=$( $sys_py_ver | cut -d' ' -f2 )
                if[ "$python_ver" != "$sys_py_ver" ]; then $install_python=true; fi
                echo $install_python