name: action-one
on: 
    workflow_dispatch:
        branches: [main]

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Upgrade system
              run: |
                sudo apt update
                echo python --version