name: action-one
on: 
    workflow_dispatch:
        branches: [main]

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Install python
              run: |
                apt update
                apt -y upgrade
                apt install -y python3-pip