name: action-one
on:
  workflow_dispatch:

env:
    python_ver: 3.2

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Check version
              run: |
                sys_py_strV=$( python --version )
                sys_py_ver=$( $sys_py_strV | cut -d' ' -f2 )
                echo $sys_py_ver
                if [ '$python_ver' == '$sys_py_ver' ]; then install_python=true; install_python=false; fi                
                echo $install_python