name: action-one
on: 
    workflow_dispatch:
        branches: [main]

env:
    python_ver: 3.2
    install_python: false

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Check version
              run: |
                sys_py_ver=$( python --version )
                sys_py_ver=$( $sys_py_ver | cut -d'' ' -f2 )
                if[ "$python_ver" != "$sys_py_ver" ]; then install_python=true; fi
            - outputs:

            - name: Upgrade System for security
              run: |
                sudo apt update
                sudo apt -y upgrade
                sudo apt install software-properties-common
                python --version

            - name: Install pip
              run: |
                sudo apt install -y python3-pip                