name: action-one
on:
  workflow_dispatch:

env:
    python_ver: 3.2

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Check version
              run: |
                sys_py_strV=$( python --version /dev/null 2>&1 )
                if [[ $sys_py_strV == *"bash"* ]]; then sys_py_strV=$( python3 --version /dev/null 2>&1 ); else sys_py_strV=$( $sys_py_strV | cut -d' ' -f2 ); fi
                if [[ $sys_py_strV == *"bash"* ]]; then install_python=true; else sys_py_strV=$( $sys_py_strV | cut -d' ' -f2 ); fi