name: action-one
on: 
    workflow_dispatch:
        branches: [main]

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Install python
              run: |
                sudo apt update
                sudo apt -y upgrade
                sudo apt install -y python3-pip