name: action-one
description: "Install a spedified version of Python"
author: "GuneetBhatia"

on: 
    workflow_dispatch:
        branches: [main]

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install python
              uses: actions/setup-python@v5
              with:
                python-version: '3.2'
              run: python my_script.py
