name: action-one
on: 
    workflow_dispatch:
        branches: [main]

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Install python
              run: |
                pip install pylint
                pip install python3
