name: action-one
on:
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '.github/worflows/*' # meaning any changes made to this location will not trigger git actions. Use 'paths' to tirgger.

env:
    python_ver: 3.2

jobs:
    job_one:
        runs-on: ubuntu-latest
        outputs:
          py_install_needed: ${{ steps.pythonV.outputs.py_install_req }}
        steps:
            - name: Check version
              id: pythonV
              run: |
                install_python="false"
                sys_py_strV=$( echo python3 --version /dev/null 2>&1 )
                if [[ $sys_py_strV == *"not found"* ]]; then sys_py_strV=$( python --version /dev/null 2>&1 ); else sys_py_strV=$( $sys_py_strV | cut -d' ' -f2 ); fi
                if [[ $sys_py_strV == *"not found"* ]]; then install_python=true; else sys_py_strV=$( $sys_py_strV | cut -d' ' -f2 ); fi
                py_install_req=echo $install_python
                echo "py_install_req=$install_python" >> "$GITHUB_OUTPUT"

    job_two:
      needs: job_one
      runs-on: ubuntu-latest
      steps:
         - name: Update system as required
           run: |
             echo "Python"
             echo {{ needs.job_one.outputs.py_install_needed }}