name: action-one
on: 
    workflow_dispatch:
        branches: [main]

jobs:
    job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Upgrade system
              run: |
                sudo apt update
                sudo apt -y upgrade
                sudo apt install software-properties-common
                echo python --version
            - name: Install pip
              run: |
                sudo apt install -y python3-pip                