name: Trigger On Specific Branch
on:
    push:
        branches:
            - main
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Demo
              run: cat /etc/os-release