name: Trigger On Specific Branch
on:
    workflow_dispatch:
        branches:
            - main
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Demo
              run: cat /etc/os-release